mongo: "mongodb://mongo:27017"
mongo_base: "admin"
mysql: "root:test@tcp(mysql:3306)/cache"
redis_address: "pub-redis-19741.eu-central-1-1.1.ec2.redislabs.com:19741"

log_hook:
    log_host: "mongodb://mongo:27017"
    log_system: plugin_service
    log_dbname: admin
    log_collection: plugin_service